services:
  wordpress1:
    image: wordpress:latest
    container_name: nodo1
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: base_master3
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp1_ #cambiar para cada nodo
  wordpress2:
    image: wordpress:latest
    container_name: nodo2
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: base_master3
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp2_ #cambiar para cada nodo
  
  wordpres3:
    image: wordpress:latest
    container_name: nodo3
    ports:
      - "8083:80"
    environment:
      WORDPRESS_DB_HOST: base_master3
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp3_ #cambiar para cada nodo
  
  base_master3:
    image: mysql:5.7
    container_name: base_master3
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE : wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    command: --log-bin=mysql-bin --binlog-format=ROW --server-id=1 
    
  base_slave3:  # contenedor esclavo
    image: mysql:5.7
    container_name: base_slave3
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: wordpress    
    command: --server-id=2 --report-host=base_slave3 --relay-log=relay-bin 
    
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php3
    ports:
      - "8080:80"
    environment:
      PMA_HOSTS : "base_master3,base_slave3"
      PMA_ARBITRARY: 1
  
  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    ports:
      - "8085:80" # Exponer el puerto 80 del contenedor
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Montar el archivo de configuración de NGINX
    depends_on:
      - wordpress1
      - wordpress2
      - wordpres3