services:
  wordpress1:
    image: wordpress:latest
    container_name: nodo1
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: base_master3
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp1_ #cambiar para cada nodo
  wordpress2:
    image: wordpress:latest
    container_name: nodo2
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: base_master3
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp2_ #cambiar para cada nodo
  
  wordpres3:
    image: wordpress:latest
    container_name: nodo3
    ports:
      - "8083:80"
    environment:
      WORDPRESS_DB_HOST: base_master3
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp3_ #cambiar para cada nodo
  
  base_master3:
     image: mysql:5.7
     container_name: base_master3
     environment:
        MYSQL_ROOT_PASSWORD : root
        MYSQL_DATABASE : wordpress
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: root
        #añadoir replicacion

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php3
    ports:
      - "8080:80"
    environment:
      PMA_HOSTS : "base_maestro3"
      PMA_ARBITRARY: 1